---
# tasks file for ../roles/internal/hassInstallFwRules

- name: Apply forward port rule (firewalld module doesn't currently support this)
  command:
    cmd: "firewall-cmd --zone={{ HostZone }} --add-forward-port=port={{ HassPort }}:proto=tcp:toport={{ HassPort }}:toaddr={{ ansible_default_ipv4.address }} --permanent"

- name: Reload the firewall rules to activate the port forwarding
  command:
    cmd: "firewall-cmd --reload"