---
# Create and Update Containser - include file

- name: Check whether container exists
  shell: "lxc list | grep {{ item }} | wc -l"
  register: lxc_list
  changed_when: "'1' not in lxc_list.stdout"

- name: Create container and apply settings
  block:
  - name: Display message to stdout when creating a container
    debug:
      msg: "Creating new container: {{ item }}"

  - name: Create container if it does not exist
    lxd_container:
      name: "{{ item }}"
      state: started
      source:
        type: image
        mode: pull
        server: "{{ img_server }}"
        protocol: simplestreams # if you get a 404, try setting protocol: simplestreams
        alias: ubuntu/focal/amd64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600
      config:
        security.nesting: "true"
        security.privileged: "true"

  - name: Ensure python3 is installed and apply config security settings
    debug:
      msg: "New container created, installing python3 and updating the container configuration file"

  - name: install python in container
    delegate_to: "{{ item }}"
    raw: /usr/bin/apt-get install -y python3

  - name: Container already exists so update the config
    lxd_container:
      name: "{{ item }}"
      config:
        security.nesting: "true"
        security.privileged: "true"
  when: lxc_list.stdout != "1"